// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgtjkwqgeeweaqcludnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBndGprd3FnZWV3ZWFxY2x1ZG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDg4MTYsImV4cCI6MjA2NzE4NDgxNn0.mSnkouA5KBS-NMG0-ztanyd9Ros_rNTbqU8KnCL-jK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});